name: Reusable Code use for deployment
on: [workflow_call, workflow_dispatch]
jobs:
    Deployment:
        runs-on: ubuntu_latest
        steps:
            - name: Output information
              run: echo "Deployemnt the code"
